### ISSUE TITLE
Federated sharing: missing notification possibility

### ISSUE THREAD

**Issue by dvh** [cs3org/OCM-API#10]
>Providers MAY inform the sending user if a share has been accepted.

I'd suggest the sending instance provides a federated sharing endpoint to receive notifications and/or is able to send a callback-URL when creating a share offer which the receiving instance can call if an offer is accepted or rejected.

**Comment by DeepDiver1975** [comment]
Since we have been talking about WebDAV in other issues as well - there is a draft for caldav notifications being worked on - https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-notifications.txt - might be interesting to think about

**Comment by glpatcern** [comment]
As a matter of fact, the `/notifications` endpoint is there for long, but the discussion is happening around https://github.com/cs3org/OCM-API/issues/46, for which there's no decision taken yet. I'm closing this issue so we follow up on the other one.
