### ISSUE TITLE
Discuss `resourceTypes[i].protocols`

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#105]
It seems `resourceTypes[i].protocols` in [discovery](https://cs3org.github.io/OCM-API/docs.html?branch=v1.1.0&repo=OCM-API&user=cs3org#/paths/~1ocm-provider/get) overlaps with the `endPoint` field there, as well as with the `protocol.webdav.URI` field in create-share. What do we want with it?

**Comment by michielbdejong** [comment]
Ah wait I think I was looking at it in the wrong way.
From https://cloud.nextcloud.com/ocm-provider:
```
{
  "enabled": true,
  "apiVersion": "1.0-proposal1",
  "endPoint": "https://cloud.nextcloud.com/ocm",
  "resourceTypes": [
    {
      "name": "file",
      "shareTypes": [
        "user",
        "group"
      ],
      "protocols": {
        "webdav": "/public.php/webdav/"
      }
    },
    {
      "name": "talk-room",
      "shareTypes": [
        "user"
      ],
      "protocols": {
        "talk-v1": "/ocs/v2.php/apps/spreed/api/"
      }
    }
  ]
}
```

So the endpoints would be:
* OCM: https://cloud.nextcloud.com/ocm
* WebDAV: https://cloud.nextcloud.com/public.php/webdav/
* Talk: https://cloud.nextcloud.com/ocs/v2.php/apps/spreed/api/

OK, I'll document it as such, noting that the WebDAV endpoint is only needed if `protocol.webdav.URI` is missing from a create-share request.

**Comment by glpatcern** [comment]
That's right, but let's not forget we also included a full URI in the create-share webdav payload.
