### ISSUE TITLE
Make the spec more modular and backwards compatible?

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#106]
We can make a few syntactical changes but we need to understand how much they introduce new code paths and break existing implementations. For instance, the switch from `/ocm-provider` to `/.well-known/ocm` is almost purely aesthetic, and instead of simplifying things, in practice it may mean everybody needs to support everything.

I have the same worry about the access code, but I think it can be avoided if we use capabilities in discovery wherever we can.

For instance, if a server doesn't advertise support for `multi` then it only needs to support `webdav` as the protocol.
And if it doesn't advertise support for `code` then it only needs to support `sharedSecret` for the access token.

Let's discuss on Thursday!

**Comment by michielbdejong** [comment]
I'll try to embed this approach into #99

**Comment by michielbdejong** [comment]
See https://github.com/cs3org/OCM-API/issues/121#issuecomment-2333416021 for a draft of how this could look

**Comment by glpatcern** [comment]
I take the liberty to close this one, given the state of the IETF draft
