### ISSUE TITLE
Note multiple API endpoint base paths in spec.yaml

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#118]
In spec.yaml we define:
* `https://<discovery-fqdn>/.well-known/ocm`
* `https://<discovery-fqdn>/ocm-provider`
* `https://<ocm-fqdn>/<ocm-base-path>/shares`
* `https://<ocm-fqdn>/<ocm-base-path>/notifications`
* `https://<ocm-fqdn>/<ocm-base-path>/invite-accepted`

(`<discovery-fqdn>` = is an OCM server's `<fqdn>` or fallback to whatever FQDN its SRV DNS record redirects to)
(`<ocm-fqdn>` and `<ocm-base-path>` come from discovery `endPoint` value)

We should make it clear that the two discovery endpoints live on a different base URL than the three API endpoints.

**Comment by glpatcern** [comment]
This was closed at some stage, the spec now mentions `discovery-fqdn` only.
