### ISSUE TITLE
SRV DNS record + keyId = a bit of a mess

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#119]
We generally assume that an OCM server is referred to by a single unique FQDN, e.g. `cernbox.cern.ch`.

The optional mechanism to add an SRV DNS record to `cern.ch` that points to `cernbox.cern.ch` could mess up the determination of the FQDN of an OCM Server for use in OCM Addresses and in Invite Acceptance Requests (recipientProvider field there).

To avoid this getting messy, we should make it clear that `einstein@cern.ch` is only a vanity alias for `einstein@cernbox.cern.ch` and not a synonym to be stored in address books or used in API calls.

This goes both for places in the body of an API call where the server's FQDN appears, as for the keyId used in httpsig.

If we fail to keep this clear then a Receiving Server may end up trusting requests from `cern.ch` but not from `cernbox.cern.ch` so it would reject all signed requests and things would break.

**Comment by michielbdejong** [comment]
I'll reword the section about discovery so that:
* the fallback to SRV is only described in the context of 'Vanity OCM Addresses'
* it is required to first try *both* /.well-known/ocm and /ocm-provider, before falling back to OCM lookup
* If following an SRV redirect, neither the Vanity OCM Address nor its FQDN should be used in any OCM API calls or httpsig keyIds.

**Comment by glpatcern** [comment]
This was superseded by #134
