### ISSUE TITLE
Calling `mfa-enforced` a permission feels weird

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#126]
https://github.com/cs3org/OCM-API/blob/ddb16c55ff810e910be1ebd826f9731020538a08/spec.yaml#L515-L517

Permissions would usually be an additive list of modes of access, such a 'read' and 'write'.

But 'mfa-enforced' is intended to limit access by adding a requirement, not adding an option to the list of allowed access modes.

**Comment by glpatcern** [comment]
Fixed by #132
