### ISSUE TITLE
Why application/x-www-url-encoded

### ISSUE THREAD

**Issue by labkode** [cs3org/OCM-API#13]
The API relies on formData for data submission.

What is the reason for choosing this encoding over JSON? JSON allows expressing complex data structures in a simple and more efficient way than `application/x-www-url-encoded`. 

If the API were only based on POST and GET methods I could understand the use of this encoding but the API is REST oriented and contains PUT and DELETE methods that are not supported by XHTML 1.x forms.

Responses are given in JSON, why not consolidate on just one encoding format?

**Comment by joostfarla** [comment]
Agreed!

I've recently started a similar discussion for a project at SURFnet: https://github.com/open-education-api/specification/issues/1

Quote:

> We have 2 options here:
> 
> **application/x-www-form-urlencoded**
> 
> Similar to the format of HTTP query parameters but as a payload. For example, `foo=1&bar=value`
> 
> This is the default content type for HTML forms submitted by web browsers. Please note that an HTML form will typically not post directly to the API. Normally this is handled by a client (Javascript) or server application.
> 
> Cons:
> - Limited support for nested fields. You have to do tricks with arrays or comma-separated values.
> - There are multiple ways (workarounds) to send these kinds of complex structures. This has to be defined & documented properly, which makes it more complex for the developer.
> 
> **application/json**
> 
> Pros:
> - Support for complex structures (nesting, arrays, etc)
> - Easier to work with:
>   - Native support in Javascript (JSON stands for JavaScript Object Notation) and other development platforms
>   - You can send the current JSON representation directly without converting it to some other media type
> - JSON supports (basic) data types: strings, numbers, booleans, null values etc
> - Easy to validate against JSON schema (which is the way parameters are defined in the OpenAPI spec)
> 
> It is possible to support both, but I would suggest to pick one.

**Comment by dvh** [comment]
Decided to use `application/json` bodies in the current spec.
