### ISSUE TITLE
Rethink capability name `/mfa-capable`

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#133]
We can change the string `/mfa-capable` to something without a leading slash. 
Also, the 'capable' is already implied by the fact that this string appears in a list of capabilities
And maybe we want to add _what_ the server is capable of doing. It's not only capable of MFA, we want it to be able to securely and reliably enforce an MFA requirement on a share.
So maybe something like 'mfa-requirement' or 'enforce-mfa-requirements'?

**Comment by glpatcern** [comment]
I think the bigger picture is well summarized in https://github.com/cs3org/OCM-API/issues/121
