### ISSUE TITLE
Email field in the invite flow

### ISSUE THREAD

**Issue by MahdiBaghbani** [cs3org/OCM-API#142]
The OCM specification has the field `email` in both `Invite Acceptance Request` and `Invite Acceptance Response`. From the wording of the Internet-Draft, I understand that this field is not optional.

I have seen cases in Nextcloud and ownCloud/oCIS (even in some R&D implementations like Aver) that which the user doesn't have an email or doesn't bother to add one, or for some other reasons (eg: privacy) refuses to do so.

I propose to make this field `Optional` in the specification.

**Comment by glpatcern** [comment]
This essentially is a duplicate of #117
