### ISSUE TITLE
OCM does not cover revoking invitations

### ISSUE THREAD

**Issue by butonic** [cs3org/OCM-API#147]
We can currently only send invites to remote instances, but I do not see a way to notify a remote instance that an invite was revoked.

Might be out of scope, but we stumbled over this during QA.

**Comment by glpatcern** [comment]
hey @butonic, in fact that would be covered by (optional) notifications:

https://github.com/cs3org/OCM-API/blob/develop/spec.yaml#L664

Where `USER_REMOVED` would tell the other end about this revocation. Yet, as far as I know no EFSS implements this.
