### ISSUE TITLE
Path-to-resource examples in Share endpoint

### ISSUE THREAD

**Issue by glpatcern** [cs3org/OCM-API#157]
Following today's meeting, I realize my own confusion with the paths given as examples in the `/share` endpoint, which should be corrected:

* When sending off a share, the path should be to the shared resource, nothing more, that is for example `/dav/ocm/<some-uuid>` (already dropping the host here).
* The receiver is expected to compose the URL as in OCM 1.0, and MAY issue requests such as `PROPFIND https://<webdav-fqdn-as-advertised-in-discovery>/dav/ocm/<some-uuid>/some/relative/path/to/resource.txt`, with a bearer token
* The sharing end is expected to support such "targeted" HTTP requests

I propose to amend the example to clarify that.

And at this point... We may well get closer to the OCM 1.0 principle, where the share payload contains just a `sharedKey` and a `sharedSecret` (not just the secret - the key here is really for lookup, so it ends up being logged, and the secret is the bearer token, with the option of a `code`), and the receiver is expected to compose the URL as:

`https://<discovered-fqdn>/<webdav-root-from-discovery>/<sharedKey>/relative/path/to/resource.txt`

This should simplify the ongoing work with Nextcloud, and it requires a minor amendment of Reva where we have to issue a discovery request (which we MUST do for security reasons) and store in the DB the full URL as opposed to just having it ready in the payload.

I confess I'd prefer `shareKey` instead of `sharedKey`, if we were to go this way, but we already have `sharedSecret`...

@michielbdejong @mickenordin @MahdiBaghbani comments?

**Comment by mickenordin** [comment]
For me I think a pr would be good, this sounds right to me, but seeing it in action with a diff would be good.

**Comment by glpatcern** [comment]
That's right, and in doing so I have a "struggle" between ensuring backwards compatibility with OCM 1.1 and simplifying the protocol. For now I'm trying to preserve backwards compatibility to a good extent.

**Comment by michielbdejong** [comment]
I agree that [the examples in Share endpoint](https://github.com/cs3org/OCM-API/blob/17d77107a39fe4e548d4f8a14e92c8e2cf8c9c34/spec.yaml#L630) are incorrect.

I think [the description for `protocol.webdav.uri`](https://github.com/cs3org/OCM-API/blob/17d77107a39fe4e548d4f8a14e92c8e2cf8c9c34/spec.yaml#L552-L557) is also incorrect.

I think I agree with your "should be corrected" bullets (not sure why `/dav/ocm` is hardcoded there but that may be my misunderstanding?) but not with your "And at this point... We may well" proposal.

In [the capability for `webdav-uri`](https://github.com/cs3org/OCM-API/pull/136/files#diff-371e2d091f4292c62681d09a829854e2834ac93a195d6e17727927f9f0bf1344R280) I described it as 'append a relative URI to the path listed for WebDAV in the appropriate `resourceTypes` entry'

**Comment by glpatcern** [comment]
> (not sure why `/dav/ocm` is hardcoded there but that may be my misunderstanding?) but not with your "And at this point... We may well" proposal.

The `/dav/ocm` is just an example, nothing hardcoded, and yes having seen also how the `webdav-uri` is described, I think it makes sense to keep `uri` as is and just recommend it to be relative - which eventually is what I have done in the PR. I'll review it for consistency and then it's good to go.
