### ISSUE TITLE
subfiles parameter when getting shares

### ISSUE THREAD

**Issue by labkode** [cs3org/OCM-API#16]
Listing shares with the subfiles parameter can be very costly. 
Is it critical to have that functionality or is just a funny feature to show a shared icon on top level folders of user directory if some children have been shared?

To be discussed on follow-up call.

**Comment by LukasReschke** [comment]
@schiessle FYI. Care to comment on that?

**Comment by michielbdejong** [comment]
I can't find any documentation about the subfiles parameter, it seems that it was indeed removed at the time, and not currently part of the OCM spec. Closing.
