### ISSUE TITLE
subadmin endpoints are really needed?

### ISSUE THREAD

**Issue by labkode** [cs3org/OCM-API#17]
From my point of view in the provisioning API the *subadmin endpoints* are very tight to ownCloud/NextCloud implementations and could be avoided. These endpoints just promote users to be part of some admin groups but this logic is not used in other endpoints, as a result of this, such logic can be moved to particular implementations that will know if the user/group has admin privileges.

**Comment by LukasReschke** [comment]
I'm too in favour of removing anything non-sharing related from here. That's application specific logic. 

Something required from my opinion though is to make sure the API itself is extensible with vendor custom functionalities.

**Comment by glpatcern** [comment]
This was eventually removed from the specs long ago, closing
