### ISSUE TITLE
application module

### ISSUE THREAD

**Issue by labkode** [cs3org/OCM-API#18]
The application endpoints are very ownCloud/NextCloud related. A better endpoint would be a capabilities one where clients could check which modules of the spec (shares, federatedsharing, privatedata ..) are enabled or not to behave accordingly. 

Is this the objective of the application endpoint?

**Comment by karlitschek** [comment]
So the idea is that a server first queries the /ocs-provider/ endpoint which provides the realy API endpoints. This gives different implementation the needed flexibility because of different architectures or technologies.

**Comment by DeepDiver1975** [comment]
> The application endpoints are very ownCloud/NextCloud related. A better endpoint would be a capabilities one where clients could check which modules of the spec (shares, federatedsharing, privatedata ..) are enabled or not to behave accordingly.
> 
> Is this the objective of the application endpoint?

WebDAV e.g. handles this within responses to OPTION requests. Furthermore a simple NotFound to an API endpoint can let the client know that this feature is not enabled.

> So the idea is that a server first queries the /ocs-provider/ endpoint which provides the realy API endpoints. This gives different implementation the needed flexibility because of different architectures or technologies.

From my pov this is service discovery which is handled by the well-known RFC - https://tools.ietf.org/html/rfc5785 - no need to invent something new.

**Comment by dvh** [comment]
Added the `wontfix` label because it's out of scope.

**Comment by DeepDiver1975** [comment]
> Added the wontfix label because it's out of scope.

service discovery should be part of the spec from my pov

**Comment by dvh** [comment]
Reopened for further discussion, we'll use the Projects feature to determine scope.

**Comment by glpatcern** [comment]
Closed by https://github.com/cs3org/OCM-API/pull/59
