### ISSUE TITLE
Typos here and there

### ISSUE THREAD

**Issue by labkode** [cs3org/OCM-API#19]
* The Update for a share has typos (it says get information about a share)
* Get group memberships and get members of groups data attributes are wrong. It should be viceversa.

**Comment by dvh** [comment]
> The Update for a share has typos (it says get information about a share)

That's already fixed but it's cached quiet aggresively ;-)

> Get group memberships and get members of groups data attributes are wrong. It should be viceversa.

This is taken from the original docs. Objective is to 'shoot' at it now it's converted to Open API Spec.

**Comment by dvh** [comment]
Added the `wontfix` label because it's out of scope

**Comment by dvh** [comment]
Reopened for further discussion, we'll use the Projects feature to determine scope.

**Comment by glpatcern** [comment]
Obsoleted
