### ISSUE TITLE
Existing standards

### ISSUE THREAD

**Issue by labkode** [cs3org/OCM-API#21]
There are already existing standards that we could use/be based on them:

- File management: WebDAV, [remoteStorage](https://remotestorage.io/)
- Full user and group management (CRUD):  [System for Cross-domain Identity Management (SCIM)](http://www.simplecloud.info/)

For using WebDAV as synchronisation protocol there are already documents here:
[https://github.com/labkode/Internet-Storage-Sync/blob/master/applicability-of-webdav.md](https://github.com/labkode/Internet-Storage-Sync/blob/master/applicability-of-webdav.md)

Also, is worth looking into this for pros/cons of WebDAV vs REST for syncing:

* [https://tools.ietf.org/html/draft-cui-iss-problem-03](https://tools.ietf.org/html/draft-cui-iss-problem-03)
* [https://mailarchive.ietf.org/arch/search/?email_list=storagesync](https://mailarchive.ietf.org/arch/search/?email_list=storagesync)

**Comment by moscicki** [comment]
Here is the one currently used by owncloud and nextcloud: https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md

**Comment by DeepDiver1975** [comment]
> Also, is worth looking into this for pros/cons of WebDAV vs REST for syncing:

WebDAV already provides a specification for Syncronization of resource collections: https://tools.ietf.org/html/rfc6578

This is the basis for CalDAV and CardDAV synchronization which from my pov has been proved to work in this aread for quite some years now.

**Comment by dragotin** [comment]
@DeepDiver1975 I haven't read through all the RFC so far, but do you know if it supports MOVE?

**Comment by DeepDiver1975** [comment]
@dragotin https://tools.ietf.org/html/rfc6578#section-3.5.1 is explicitly talking about COPY MOVE and BIND - but there seems to be no explicit status/information on the operation.

Basically the result of this sync report is a list of changed (including added) and deleted resources.

For detection of MOVE we need to use additional properites like we do today with the fileid.

**Comment by michielbdejong** [comment]
Thanks for the mention of remoteStorage! :)
Current OCM is [multi-protocol](https://github.com/cs3org/OCM-API/pull/93/files#diff-9cfca4a1b73e1e28e30fb9b0b984aad6d4caaf0819c61ed40ad338600531f745R354-R357) for the actual resource sync,
and we did another thorough analysis of [relationship to OAuth and Fediverse](https://github.com/cs3org/OCM-API/issues/84) recently so I think we can close this issue now.
