### ISSUE TITLE
Notifications endpoint might also return a 202 accepted

### ISSUE THREAD

**Issue by dvh** [cs3org/OCM-API#31]
At the moment we assume that the only valid success response is a `201 Created`. However, if the receiver wants to process the notification in another way, it might also return a `202 Accepted` response to inform the sender that the notification has been received but it's not possible for the receiver to fetch the notification later, because the receiver implemented it's own notification handler.

**Comment by michielbdejong** [comment]
The side-effects of notifications have always been a slightly confusing part of OCM. I interpret the word 'notification' to mean that no report of completion of the actions it triggers is necessary. In fact, we consider those triggered actions as 'side effects' and not as 'completion of the request'.

For example if I notify you "your house is on fire" you may respond "201 thanks for the heads-up!", that's a notification.
But if I send you "please extinguish the fire in your house" then that is not a notification but an API request, and you may respond "202 accepted".

With that analysis, and as @glpatcern mentioned in #77  this would be a breaking change, let's keep things as they are for now, closing.

**Comment by michielbdejong** [comment]
(see also [discussion of notifications as a general collection for "anything you might do"](https://github.com/cs3org/OCM-API/issues/34#issuecomment-281103310))
