### ISSUE TITLE
Server alias

### ISSUE THREAD

**Issue by diocas** [cs3org/OCM-API#38]
In order to improve the usability, it might be useful to provide a way to set aliases for a service, allowing users to share using that alias instead of the full url of the service.

Imagine the case of CERNBox: the service is deployed at `cernbox.cern.ch`, and this should be the endpoint used for auto discovery/getting information about the service (we're not planning to put this information in the top domain, which is not controlled by us). In the current model, a user would have to put `username_or_email@cernbox.cern.ch` to share something, which is not intuitive. If we set "cern.ch" as an alias, then it would be possible to share with `username_or_email@cern.ch`- which is generally the way users know each other -, and the client would contact `cernbox.cern.ch`. 

All of this is assuming that the services are configured manually, since - as I understood - you, as a sysadmin, need to approve it first.

**Comment by glpatcern** [comment]
Resurrecting this issue from the old days, this is addressed by the DNS SRV record described in #82.
