### ISSUE TITLE
Does OCM-API have any roadmap or plans for future development?

### ISSUE THREAD

**Issue by sunjam** [cs3org/OCM-API#43]
I'm curious about any future development of this great idea.  [Forum discussion here](https://help.nextcloud.com/t/mirroring-of-two-nextcloud-server/52564/12?u=just).
Got any plans to come back to it?

Pull requests [37](https://github.com/cs3org/OCM-API/pull/37), [41](https://github.com/cs3org/OCM-API/pull/41), and [40](https://github.com/cs3org/OCM-API/pull/40)

**Comment by michielbdejong** [comment]
Yes! You can follow along in https://gitter.im/cs3org/OCM
We tagged version 1.0 and I'm writing a test suite for it.

**Comment by glpatcern** [comment]
I think with the recent activity and the follow up discussions these days at [CS3 Barcelona](https://indico.cern.ch/event/1210538/program), the answer is clear. Feel free to contribute or contact us!

**Comment by sunjam** [comment]
Can you please clarify the recent activity or link to any recent
development, such as any results from the conference that are now in the
works.  Thanks.

**Comment by glpatcern** [comment]
For recent activity, just have a look at recent PRs such as #54 57 #59 #61. And you can look for 'OCM' on the conference page I linked before. More proceedings to come ...
