### ISSUE TITLE
Activate GitHub Pages feature on this repo

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#47]
@labkode thanks for merging my PR!
Could you maybe activate the GitHub Pages feature in the Settings of this repo?
Then https://cs3org.github.io/OCM-API/docs.html
Will look like https://michielbdejong.github.io/OCM-API/docs.html

**Comment by labkode** [comment]
@michielbdejong , sure ! I'll point to develop branch.

**Comment by labkode** [comment]
@michielbdejong we may need to put the html documentation in `index.html` file instead under root of the repo or under `docs/index.html`

**Comment by labkode** [comment]
@michielbdejong  looks it wasn't needed at all:
https://cs3org.github.io/OCM-API/ 
looks good to me

**Comment by michielbdejong** [comment]
\o/
Thanks a bundle!
