### ISSUE TITLE
Document meshProvider field in NewShare

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#50]
Reva [uses](https://github.com/cs3org/reva/blob/master/internal/http/services/ocmd/shares.go#L63) a `meshProvider` field.

I'm not sure which value to specify there.

**Comment by michielbdejong** [comment]
Ah, apparently it should be the `domain` of the provider, not its `name`. So for instance `cernbox.cern.ch`, not `cernbox`.
See https://github.com/cs3org/reva/blob/master/examples/ocmd/providers.demo.json#L6

**Comment by michielbdejong** [comment]
Still, this feels like something to document in the spec!

**Comment by glpatcern** [comment]
I had overlooked this, but with the latest refactoring in #57 I think this is now obsolete.
