### ISSUE TITLE
Group-owned shares and invites to/from groups

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#53]
OCM assumes the sender of a share is a specific user. But in some situations it would be useful to think of shares as owned by a group.

This would mirror the concept of "Group Folders" which exists in some EFSS systems, but across multiple sites.

**Comment by michielbdejong** [comment]
Also, share-to-group is possible in the share-with flow of OCM but not in the invite-first flow. We need to think more about this.

One blocking factor in working on this is that the invite-first flow is so far only implemented in Reva, and I think Reva's groups support [is not very extensive yet](https://github.com/cs3org/reva/issues/3653) (at least in the master branch).

**Comment by smesterheide** [comment]
Are group owned shares any different from re-shares? Consider a resource (file or folder) owned by a particular user that is being shared with a group. Any member can request to re-share the resource with other users or groups (local or remote) given the necessary permissions. The resource gains more independent shares during the process. In Nextcloud re-shares are handled by the instance that the owner user is home to (notification type REQUEST_RESHARE).

**Comment by michielbdejong** [comment]
Yes, I think there is a difference. It removes the need to assign a particular group member as the "owner".
So something like https://apps.nextcloud.com/apps/groupfolders / https://www.youtube.com/watch?v=LaTd-TTj41Q but cross-server! :)
