### ISSUE TITLE
support sub-shares?

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#75]
What if you for instance get read access to /foo but write access to /foo/bar? In OCM that would be two separate shares, and if you open /foo and then drill down to /foo/bar, the receiving server will not recognise that you entered the folder where you do have read/write

**Comment by smesterheide** [comment]
Seems right on the surface, `/foo/bar` is more specific than `/foo`. My question here is are we going to mimic POSIX file system permissions?

**Comment by glpatcern** [comment]
[Reviewing all outstanding issues] this is IMHO implementation-dependent, meaning that we may well have OCM implementations that use some POSIX-like ACLs and do the "right thing" (in the example, give write access to `/foo/bar` even when browsing from a read-only `/foo` folder).

As an example, this is how EOS works and how CERNBox exposes OCM shares.

The question is whether we want the spec to explicitly state what is the "right thing" to do, or whether to leave this aspect deliberately unspecified.
