### ISSUE TITLE
Private data: endpoints for operations

### ISSUE THREAD

**Issue by dvh** [cs3org/OCM-API#8]
1. There are different endpoints for `GET`, `POST` and `DELETE`, but the method itself should be enough to indicate the intended operation on the private data endpoint:

    - `GET /privatedata/{storename}/{key}` instead of `GET /privatedata/getattribute/{storename}/{key}`
    - `POST /privatedata/{storename}/{key}` instead of `GET /privatedata/setattribute/{storename}/{key}`
    - `DELETE /privatedata/{storename}/{key}` instead of `GET /privatedata/deleteattribute/{storename}/{key}`

1. Should there also be `GET /privatedata` and `GET /privatedata/{storename}` endpoints to explore what's in there?

**Comment by DeepDiver1975** [comment]
I absolutely agree on the change of the route specification.
But I question if this is a needed api within the scope of cloud federation.

**Comment by dvh** [comment]
Added `wontfix` label because it's out of scope.

**Comment by dvh** [comment]
Reopened for further discussion, we'll use the Projects feature to determine scope.

**Comment by glpatcern** [comment]
Obsoleted
