### ISSUE TITLE
Trade in shared secret for an OAuth-grade refresh/access token?

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#81]
We could benefit from OAuth best practices if we frame OCM as a pro-active flavour of OAuth.
The resource owner pro-actively gives the client access and sends them a shared secret via OCM.
After that, the current practice is that the client would then use this secret as-is to access the resource API (WebDAV or otherwise).
It might be better if we use the OAuth framework to make sure this client secret is not included in each network request.

**Comment by michielbdejong** [comment]
See also #80

**Comment by michielbdejong** [comment]
So we would remove https://github.com/cs3org/OCM-API/blob/b45c7a0016bf4520b7fe4c41b1cad0989b6aeba5/spec.yaml#L465-L469
And then instead the flows would be something like this:
* invite-first, and public-link and share-with flows happen the same way as usual, with the difference that `sharedSecret` is left out
* the receiving server requests access to the resource, acting as an OAuth client at this point
* the sending server recognises the domain name of the receiving server and gives out access
* The [Client Credentials Grant](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4) seems appropriate here, but there might be other options - to be discussed
* the receiving server can now access the resource

**Comment by michielbdejong** [comment]
I'm not sure if we should push for this without a proactive ask for it from vendors. Will close it until someone asks for this option to be added.

**Comment by butonic** [comment]
This is a blocker for oCIS. I'll try to clarify our requirements next week.
