### ISSUE TITLE
Milestone 5 "spec text development"

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#99]
Write a proper Internet Draft, submit to IETF

**Comment by michielbdejong** [comment]
I think we should probably write four specs:
* client instance discovery for GNAP
* end user discovery for GNAP
* resource notifications for GNAP
* Open Cloud Mesh (putting it all together but adding as little as possible original content in itself)

**Comment by michielbdejong** [comment]
We should also research how the fediverse does client instance discovery and end user discovery.

**Comment by michielbdejong** [comment]
Lots of new thoughts since last week. No need to add a dependency on GNAP I think, since OCM is really somewhere between authorization and fediverse. I think we can write a single spec that first describes the strictest version that everyone should support, and then add extensions from there.

Rough idea for sections:

* creating a share, using httpsig+bearer tokens
* other / multiple protocols, extra (legacy) fields
* dynamic client registration, discovery (/.well-known/ocm, /ocm-provider, DNS SRV)
* recipient user/group discovery, invites
* flows
* accept/reject/revoke notifications
* reshare notifications

**Comment by michielbdejong** [comment]
I did some work on this today in #103. Will continue tomorrow.

**Comment by michielbdejong** [comment]
I'm now trying to split this up into smaller, reviewable PRs - will add to this list as I progress:
* #109

**Comment by glpatcern** [comment]
I think this can be closed for good, after having published the IETF draft!
